language: python

python:
 - "3.6"

install:
 - pip3 install -r requirements.txt

services:
- postgresql

before_script:
- export FLASK_APP=run.py
- export FLASK_ENV=testing
- psql -c 'create database send_it;' -U postgres
- export DATABASE_URL="dbname='send' host='localhost' port='5432' user='postgres' password=''"
- export DATABASE_URL="dbname='test_send' host='localhost' port='5432' user='postgres' password=''"

 script:
  - pytest --cov=app/

after_success: coveralls

