language: python

python:
 - "3.6"

install:
 - pip install -r requirements.txt
 - pip install coveralls
 - pip install psycopg2-binary

services:
- postgresql

before_script:
- export FLASK_ENV=testing
- psql -c 'create database test_send;' -U postgres
- export DATABASE_URL="postgresql://postgres@localhost:5432/test_send"


 script:
  - nosetests --with-coverage --cover-package=app

after_success: coveralls

