language: python

python:
 - "3.6"

install:
 - pip3 install -r requirements.txt

services:
- postgresql

before_script:
- export FLASK_APP=run.py
- psql -c 'create database test_send;' -U postgres
- export DATABSE_URL="dbname='test_send' host='localhost' port='5432' user='postgres' password= '' "
- export FLASK_ENV=testing
- flask migrate

script: coverage run --source=api -m pytest && coverage report

after_success: coveralls

notifications:
 email: false
